Q1. Pearson correlation coefficient is a measure of the linear relationship between two variables. Suppose
you have collected data on the amount of time students spend studying for an exam and their final exam
scores. Calculate the Pearson correlation coefficient between these two variables and interpret the result.

In [1]:
import pandas as pd

In [2]:
df_stud=pd.DataFrame({"Time_Studying":[1,2,3,4,6,5,3,2,4,5],"Scores":[45,50,56,70,88,75,61,54,48,90]})

In [3]:
df_stud

Time_Studying  Scores
0              1      45
1              2      50
2              3      56
3              4      70
4              6      88
5              5      75
6              3      61
7              2      54
8              4      48
9              5      90

In [4]:
df_stud.corr(method="pearson")

Time_Studying    Scores
Time_Studying       1.000000  0.859569
Scores              0.859569  1.000000

In [5]:
## From above we can observe that Time studying has high positive corelation with scores of students(.85)

In [6]:
## More is the study time, higher is the marks

Q2. Spearman's rank correlation is a measure of the monotonic relationship between two variables.
Suppose you have collected data on the amount of sleep individuals get each night and their overall job
satisfaction level on a scale of 1 to 10. Calculate the Spearman's rank correlation between these two
variables and interpret the result.

In [7]:
df_job=pd.DataFrame({"sleep_time":[6,5,7,4,8,9,5,6,3,7],"Job_Satisfaction":[7,5,8,4,6,9,6,7,2,8]})

In [8]:
df_job

sleep_time  Job_Satisfaction
0           6                 7
1           5                 5
2           7                 8
3           4                 4
4           8                 6
5           9                 9
6           5                 6
7           6                 7
8           3                 2
9           7                 8

In [9]:
df_job.corr(method='spearman')

sleep_time  Job_Satisfaction
sleep_time          1.000000          0.842593
Job_Satisfaction    0.842593          1.000000

In [10]:
## AS seen from above "amount of sleep" is very important for job satisfaction .
## both are positively correlated (.84)
## More is sleep more is the job satisfaction

Q3. Suppose you are conducting a study to examine the relationship between the number of hours of
exercise per week and body mass index (BMI) in a sample of adults. You collected data on both variables
for 50 participants. Calculate the Pearson correlation coefficient and the Spearman's rank correlation
between these two variables and compare the results.

In [11]:
import numpy as np

In [12]:
x=np.random.randint(16,35,50)

In [42]:
x1=x.copy()

In [43]:
x1

array([23, 24, 18, 29, 22, 24, 28, 16, 23, 21, 33, 28, 27, 34, 19, 23, 27,
       28, 16, 30, 22, 16, 27, 25, 34, 19, 31, 19, 34, 28, 32, 33, 25, 30,
       19, 29, 34, 27, 33, 19, 25, 29, 21, 23, 29, 17, 30, 18, 16, 20])

In [13]:
x

array([23, 24, 18, 29, 22, 24, 28, 16, 23, 21, 33, 28, 27, 34, 19, 23, 27,
       28, 16, 30, 22, 16, 27, 25, 34, 19, 31, 19, 34, 28, 32, 33, 25, 30,
       19, 29, 34, 27, 33, 19, 25, 29, 21, 23, 29, 17, 30, 18, 16, 20])

In [44]:
y=[11,9,6,2,8,9,3,2,11,9,1,3,3,1,9,12,5,5,4,2,11,5,5,7,1,9,2,9,1,7,2,1,10,2,10,3,2,5,1,9,11,5,9,11,5,4,2,8,4,9]

In [45]:
len(y)

50

In [46]:
df_excercise=pd.DataFrame({'Time_spent_excercise':y,'BMI':x1})

In [47]:
df_excercise.head()

Time_spent_excercise  BMI
0                    11   23
1                     9   24
2                     6   18
3                     2   29
4                     8   22

In [48]:
df_excercise.corr(method='pearson')

Time_spent_excercise       BMI
Time_spent_excercise              1.000000 -0.603367
BMI                              -0.603367  1.000000

In [49]:
df_excercise.corr(method='spearman')

Time_spent_excercise       BMI
Time_spent_excercise              1.000000 -0.636928
BMI                              -0.636928  1.000000

In [20]:
## From above it is infered that Time Spent Excercise and BMI are negatively correlated
## But as we know that excercise will have a greater impact on BMI 
## Here this happens due to the reason that BMI has normal range (18.5 – 24.9) , below 18.5 has underweight and above 25 will have obesity problems
## BMI will not increase as we do more and more excercise it will be within range, if it goes above range then its obesity,
## Almost Pearson and Spearman rank Correlation has almost same results

Q4. A researcher is interested in examining the relationship between the number of hours individuals
spend watching television per day and their level of physical activity. The researcher collected data on
both variables from a sample of 50 participants. Calculate the Pearson correlation coefficient between
these two variables.

In [21]:
t1=np.random.randint(1,10,50)

In [22]:
t1

array([1, 7, 3, 7, 9, 5, 6, 8, 7, 8, 7, 4, 5, 2, 3, 8, 3, 5, 1, 3, 7, 5,
       2, 5, 1, 4, 8, 8, 7, 7, 9, 9, 9, 2, 4, 8, 8, 1, 6, 9, 9, 8, 3, 5,
       7, 9, 7, 9, 5, 9])

In [23]:
## Here level of physical activity ranges from 1 to 10 (1 being lowest activity and 10 being highest)
activity=10-t1

In [24]:
activity

array([9, 3, 7, 3, 1, 5, 4, 2, 3, 2, 3, 6, 5, 8, 7, 2, 7, 5, 9, 7, 3, 5,
       8, 5, 9, 6, 2, 2, 3, 3, 1, 1, 1, 8, 6, 2, 2, 9, 4, 1, 1, 2, 7, 5,
       3, 1, 3, 1, 5, 1])

In [25]:
df_pyhsical=pd.DataFrame({"Time_Wathcing_Television":t1,"Level_of_Pyhsical_Activity":activity})

In [26]:
df_pyhsical.head()

Time_Wathcing_Television  Level_of_Pyhsical_Activity
0                         1                           9
1                         7                           3
2                         3                           7
3                         7                           3
4                         9                           1

In [27]:
df_pyhsical.corr(method='pearson')

Time_Wathcing_Television  \
Time_Wathcing_Television                         1.0   
Level_of_Pyhsical_Activity                      -1.0   

                            Level_of_Pyhsical_Activity  
Time_Wathcing_Television                          -1.0  
Level_of_Pyhsical_Activity                         1.0

In [28]:
## Time_spent watching televison and Level of Physical activity has negative correlation

Q5. A survey was conducted to examine the relationship between age and preference for a particular
brand of soft drink. The survey results are shown below:

In [29]:
## Since above question Didnt specify what needs to be done and as confimred from Ineuron support Team skipping the Question

Q6. A company is interested in examining the relationship between the number of sales calls made per day
and the number of sales made per week. The company collected data on both variables from a sample of
30 sales representatives. Calculate the Pearson correlation coefficient between these two variables.

In [32]:
sales_call=np.random.randint(10,50,30)

In [33]:
sales_call

array([22, 28, 33, 44, 29, 14, 25, 14, 37, 17, 31, 15, 24, 46, 20, 32, 15,
       47, 46, 35, 24, 42, 29, 17, 15, 29, 32, 41, 13, 32])

In [36]:
sales_made=[5,7,8,14,8,3,6,4,12,6,10,3,6,16,5,10,3,20,18,11,8,15,7,3,2,5,10,13,5,9]

In [37]:
len(sales_made)

30

In [38]:
df_sales=pd.DataFrame({"Sales_Call":sales_call,"Sales Done":sales_made})

In [40]:
df_sales.head()

Sales_Call  Sales Done
0          22           5
1          28           7
2          33           8
3          44          14
4          29           8

In [50]:
df_sales.corr(method='pearson')

Sales_Call  Sales Done
Sales_Call    1.000000    0.945625
Sales Done    0.945625    1.000000

In [53]:
## Number of call has high impact on sales.
## Higher is the calls higher is the sales 